import {
  Settings,
  BarChart3,
  Wrench,
  DollarSign,
  Shield,
  Building2,
  TrendingUp,
  Phone,
  Code2,
  Zap,
  Layout,
  Users,
  AlertTriangle,
} from 'lucide-react';

export const navigationZones = [
  {
    id: 'onboarding',
    label: 'Onboarding & Setup',
    icon: Layout,
    description: 'Get started: Import data, discover files, integrate Companies House',
    routes: [
      { path: '/setup', label: 'Setup Checklist', icon: '✓' },
      { path: '/data-discovery', label: 'Data Discovery Hub', icon: Zap },
      { path: '/intelligent-onboarding', label: 'Smart Onboarding', icon: '✨' },
      { path: '/bulk-import-tester', label: 'Bulk Import Tester', icon: '📤' },
      { path: '/companies-house-profiles', label: 'Companies House Sync', icon: '🏢' },
    ],
  },
  {
    id: 'core',
    label: 'Core Operations',
    icon: Wrench,
    description: 'Manage properties, units, tenants, and contacts',
    routes: [
      { path: '/dashboard', label: 'Dashboard', icon: '📊' },
      { path: '/properties', label: 'Properties', icon: '🏠' },
      { path: '/properties/add', label: 'Add Property', icon: '➕' },
      { path: '/units', label: 'Units', icon: '🏘️' },
      { path: '/tenants', label: 'Tenants', icon: '👥' },
      { path: '/contacts', label: 'Contacts', icon: '📋' },
      { path: '/companies', label: 'Companies', icon: '🏢' },
    ],
  },
  {
    id: 'operations',
    label: 'Maintenance & Operations',
    icon: Wrench,
    description: 'Maintenance requests, scheduling, forecasting, inspections',
    routes: [
      { path: '/maintenance-board', label: 'Maintenance Board', icon: '📋' },
      { path: '/maintenance', label: 'Maintenance Workflow', icon: '🔧' },
      { path: '/maintenance-scheduling', label: 'Scheduling', icon: '📅' },
      { path: '/maintenance-forecasting', label: 'Forecasting', icon: '🔮' },
      { path: '/maintenance-analytics', label: 'Analytics', icon: '📈' },
      { path: '/tasks', label: 'Task Management', icon: '✓' },
      { path: '/maintenance-reports', label: 'Reports', icon: '📊' },
      { path: '/emergency-callouts', label: 'Emergency Callouts', icon: '🚨' },
      { path: '/property-manager-dashboard', label: 'Property Manager Dashboard', icon: '👔' },
      { path: '/contractor-scheduling', label: 'Contractor Scheduling', icon: '📅' },
    ],
  },
  {
    id: 'finance',
    label: 'Finance & Accounting',
    icon: DollarSign,
    description: 'Rent, expenses, reports, bank reconciliation, invoices',
    routes: [
      { path: '/financials', label: 'Financials Overview', icon: '💰' },
      { path: '/financial-reporting', label: 'Reports Dashboard', icon: '📊' },
      { path: '/financial-reports', label: 'Custom Reports', icon: '📄' },
      { path: '/banking', label: 'Banking', icon: '🏦' },
      { path: '/bank-reconciliation', label: 'Bank Reconciliation', icon: '✓' },
      { path: '/reconciliation', label: 'Reconciliation', icon: '🔄' },
      { path: '/rent-ledger', label: 'Rent Ledger', icon: '📚' },
      { path: '/expenses', label: 'Expenses', icon: '💸' },
      { path: '/invoices', label: 'Invoices', icon: '📋' },
      { path: '/service-charges', label: 'Service Charges', icon: '🔔' },
      { path: '/ground-rent', label: 'Ground Rent', icon: '🎯' },
      { path: '/accounting', label: 'Accounting Integration', icon: '🔗' },
      { path: '/owner-financials', label: 'Owner Financial Dashboard', icon: '📊' },
      { path: '/billing', label: 'Billing', icon: '💳' },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance & Safety',
    icon: Shield,
    description: 'Certificates, risk analytics, fire safety, legal framework',
    routes: [
      { path: '/compliance-hub', label: 'Compliance Hub', icon: Shield },
      { path: '/certificates', label: 'Certificates', icon: '📜' },
      { path: '/certificate-management', label: 'Certificate Management', icon: '✓' },
      { path: '/certificate-compliance', label: 'Certificate Compliance Tracking', icon: '🔍' },
      { path: '/compliance-risk-analytics', label: 'Risk Analytics', icon: '📉' },
      { path: '/relationship-intelligence', label: 'Relationship Intelligence (COI)', icon: '🔗' },
      { path: '/legal-compliance-framework', label: 'Legal Framework', icon: '⚖️' },
      { path: '/business-relationship-compliance', label: 'Business Relationships', icon: '🤝' },
      { path: '/compliance-audit', label: 'Compliance Audit', icon: '🔎' },
      { path: '/compliance-workflow-automation', label: 'Workflow Automation', icon: '⚙️' },
      { path: '/compliance-notification-center', label: 'Notifications', icon: '🔔' },
      { path: '/regulatory-hub', label: 'Regulatory Hub', icon: '📋' },
    ],
  },
  {
    id: 'block-management',
    label: 'Block Management',
    icon: Building2,
    description: 'Service charges, RTM, leaseholders, building safety',
    routes: [
      { path: '/block-management', label: 'Block Management Overview', icon: Building2 },
      { path: '/service-charges-management', label: 'Service Charges', icon: '💰' },
      { path: '/rtm-management', label: 'RTM Management', icon: '🏢' },
      { path: '/building-safety-register', label: 'Building Safety Register', icon: '🛡️' },
      { path: '/block-compliance-dashboard', label: 'Compliance Dashboard', icon: '✓' },
      { path: '/leaseholder-portal', label: 'Leaseholder Portal', icon: '🚪' },
      { path: '/document-automation', label: 'Document Automation', icon: '📄' },
    ],
  },
  {
    id: 'sales',
    label: 'Sales & Lettings',
    icon: TrendingUp,
    description: 'Sales dashboard, leads, viewings, lettings pipeline',
    routes: [
      { path: '/sales', label: 'Sales Dashboard', icon: TrendingUp },
      { path: '/pipeline', label: 'Lettings Pipeline', icon: '📈' },
      { path: '/viewings', label: 'Viewings', icon: '👁️' },
      { path: '/market-reports', label: 'Market Reports', icon: '📊' },
      { path: '/buyer-portal', label: 'Buyer Portal', icon: '🚪' },
      { path: '/agent-performance', label: 'Agent Performance', icon: '⭐' },
    ],
  },
  {
    id: 'tenants',
    label: 'Tenant Management',
    icon: Users,
    description: 'Tenant portal, screening, payments, communications',
    routes: [
      { path: '/tenant-portal', label: 'Tenant Portal', icon: '🚪' },
      { path: '/tenant-screening', label: 'Tenant Screening', icon: '🔍' },
      { path: '/tenant-self-service', label: 'Self-Service Portal', icon: '📱' },
      { path: '/tenant-portal-enhanced', label: 'Enhanced Portal', icon: '✨' },
      { path: '/tenant-compliance-portal', label: 'Compliance Portal', icon: '✓' },
      { path: '/tenant-communication', label: 'Communications', icon: '💬' },
      { path: '/tenant-payments', label: 'Payment Portal', icon: '💳' },
      { path: '/tenant-maintenance', label: 'Maintenance Portal', icon: '🔧' },
    ],
  },
  {
    id: 'outofhours',
    label: 'Out-of-Hours Service',
    icon: Phone,
    description: 'Call center, pipeline, reporting, pricing',
    routes: [
      { path: '/out-of-hours', label: 'Call Center', icon: Phone },
      { path: '/out-of-hours-pipeline', label: 'Service Pipeline', icon: '📈' },
      { path: '/out-of-hours-reporting', label: 'Reporting', icon: '📊' },
      { path: '/call-center-config', label: 'Configuration', icon: '⚙️' },
      { path: '/out-of-hours-pricing', label: 'Pricing', icon: '💰' },
      { path: '/out-of-hours-onboarding', label: 'Onboarding', icon: '🚀' },
      { path: '/virtual-call-center', label: 'Virtual Setup', icon: '☁️' },
      { path: '/contractor-portal', label: 'Contractor Mobile', icon: '📱' },
    ],
  },
  {
    id: 'admin',
    label: 'Admin & System',
    icon: Settings,
    description: 'Settings, integrations, documentation, monitoring',
    routes: [
      { path: '/settings', label: 'Settings', icon: Settings },
      { path: '/integrations', label: 'Integrations', icon: '🔗' },
      { path: '/api-integrations', label: 'API Integrations', icon: '⚡' },
      { path: '/document-templates', label: 'Document Templates', icon: '📄' },
      { path: '/workflows', label: 'Workflows', icon: '⚙️' },
      { path: '/automation-templates', label: 'Automation Templates', icon: Zap },
      { path: '/document-repository', label: 'Document Repository', icon: '📚' },
      { path: '/property-documents', label: 'Property Documents', icon: '🗂️' },
      { path: '/vendor-management', label: 'Vendor Management', icon: '🤝' },
      { path: '/errors', label: 'Error Monitoring', icon: AlertTriangle },
      { path: '/backup-management', label: 'Backup Management', icon: '💾' },
      { path: '/performance-metrics', label: 'Performance Metrics', icon: '📈' },
    ],
  },
  {
    id: 'developer',
    label: 'Developer Zone',
    icon: Code2,
    description: 'Developer docs, architecture, testing, demo data',
    routes: [
      { path: '/developer-documents', label: 'Developer Documentation', icon: Code2 },
      { path: '/document-upload-hub', label: 'Document Upload Hub', icon: '📤' },
      { path: '/dev-demo-switcher', label: 'Demo Data Switcher', icon: '🎭' },
      { path: '/demo-station', label: 'Demo Station', icon: '🎪' },
      { path: '/user-type-manager', label: 'User Type Manager', icon: '👤' },
    ],
  },
];