import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

const TEMPLATES = [
  // COMPLIANCE ZONE
  {
    template_id: 'cert-expiry-alert',
    name: 'Certificate Expiry Alert',
    description: 'Auto-alert 30 days before gas/electrical certificates expire',
    zone: 'compliance',
    category: 'alerts',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'daily', time: '09:00' },
    actions: [
      { action_type: 'send_email', config: { template: 'cert_expiry_30days' } },
      { action_type: 'create_task', config: { priority: 'high', title: 'Renew {{certificate_type}} Certificate' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 5,
    use_cases: ['Avoid compliance breaches', 'Stay on top of renewals', 'Reduce penalties'],
    related_entities: ['Property', 'GasSafetyCertificate', 'EICRCertificate'],
    related_functions: ['checkCertificateExpiryDaily'],
    is_popular: true,
    icon: '📜',
    color: '#dc2626',
  },
  {
    template_id: 'coi-scan-quarterly',
    name: 'Quarterly Conflict of Interest Scan',
    description: 'Auto-run COI detection on key relationships every quarter',
    zone: 'compliance',
    category: 'verification',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'quarterly', month: 'Jan' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'detectConflictsOfInterest' } },
      { action_type: 'send_email', config: { template: 'coi_scan_results' } },
    ],
    difficulty: 'medium',
    estimated_setup_time_minutes: 15,
    use_cases: ['Regulatory compliance', 'Risk management', 'Board reporting'],
    related_entities: ['OwnershipRelationship', 'CompaniesHouseProfile'],
    related_functions: ['detectConflictsOfInterest'],
    is_popular: true,
    icon: '🔗',
    color: '#dc2626',
  },
  {
    template_id: 'hmo-license-renewal-reminder',
    name: 'HMO License Renewal Reminder',
    description: 'Alert 90 days before HMO license expires',
    zone: 'compliance',
    category: 'alerts',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'daily' },
    actions: [
      { action_type: 'send_email', config: { recipient: 'hmo_officer', template: 'license_renewal_90days' } },
      { action_type: 'create_task', config: { title: 'Apply for HMO License Renewal' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 5,
    use_cases: ['Avoid license suspension', 'Plan renewal applications early'],
    related_entities: ['HMOLicense', 'Property'],
    related_functions: [],
    is_popular: false,
    icon: '🏢',
    color: '#dc2626',
  },
  {
    template_id: 'companies-house-sync-weekly',
    name: 'Weekly Companies House Sync',
    description: 'Sync all company profiles with Companies House data weekly',
    zone: 'compliance',
    category: 'integration',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'weekly', day: 'Monday', time: '08:00' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'syncCompaniesHouseDataBatch' } },
      { action_type: 'send_email', config: { template: 'sync_completed' } },
    ],
    difficulty: 'medium',
    estimated_setup_time_minutes: 10,
    use_cases: ['Keep company data current', 'Detect director changes', 'Monitor dissolved companies'],
    related_entities: ['CompaniesHouseProfile', 'Company'],
    related_functions: ['syncCompaniesHouseDataBatch'],
    is_popular: true,
    icon: '🔄',
    color: '#dc2626',
  },

  // FINANCE ZONE
  {
    template_id: 'rent-reminder-auto',
    name: 'Automated Rent Reminder',
    description: 'Send rent reminders 5 days before rent is due',
    zone: 'finance',
    category: 'notifications',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'monthly', day_offset: -5 },
    actions: [
      { action_type: 'send_email', config: { template: 'rent_reminder' } },
      { action_type: 'send_notification', config: { channel: 'tenant_portal' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 5,
    use_cases: ['Improve collection rates', 'Reduce arrears', 'Better tenant communication'],
    related_entities: ['Tenant', 'RecurringPayment'],
    related_functions: ['sendRentReminder'],
    is_popular: true,
    icon: '💰',
    color: '#16a34a',
  },
  {
    template_id: 'monthly-invoice-generation',
    name: 'Monthly Invoice Auto-Generation',
    description: 'Generate and send invoices automatically each month',
    zone: 'finance',
    category: 'reporting',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'monthly', day: '1', time: '06:00' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'generateMonthlyInvoices' } },
      { action_type: 'send_email', config: { template: 'monthly_invoice' } },
    ],
    difficulty: 'medium',
    estimated_setup_time_minutes: 20,
    use_cases: ['Streamline billing', 'Reduce manual work', 'Improve audit trail'],
    related_entities: ['Invoice', 'FinancialTransaction'],
    related_functions: ['generateMonthlyInvoices'],
    is_popular: true,
    icon: '📄',
    color: '#16a34a',
  },
  {
    template_id: 'bank-reconciliation-weekly',
    name: 'Weekly Bank Reconciliation Check',
    description: 'Auto-reconcile bank transactions every week',
    zone: 'finance',
    category: 'verification',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'weekly', day: 'Friday', time: '16:00' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'reconcileBankTransactions' } },
      { action_type: 'send_email', config: { template: 'reconciliation_status' } },
    ],
    difficulty: 'medium',
    estimated_setup_time_minutes: 15,
    use_cases: ['Maintain financial accuracy', 'Detect fraud', 'Cash flow visibility'],
    related_entities: ['BankTransaction', 'FinancialTransaction'],
    related_functions: ['reconcileBankTransactions'],
    is_popular: false,
    icon: '🏦',
    color: '#16a34a',
  },

  // OPERATIONS ZONE
  {
    template_id: 'scheduled-inspection-monthly',
    name: 'Monthly Property Inspection Schedule',
    description: 'Auto-schedule routine property inspections every month',
    zone: 'operations',
    category: 'scheduling',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'monthly', day: '15' },
    actions: [
      { action_type: 'create_event', config: { entity: 'InspectionRecord', title: 'Monthly Property Inspection' } },
      { action_type: 'send_notification', config: { recipient: 'property_manager' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 10,
    use_cases: ['Detect maintenance early', 'Document condition', 'Protect deposit disputes'],
    related_entities: ['InspectionRecord', 'Property'],
    related_functions: ['scheduleInspection'],
    is_popular: true,
    icon: '📅',
    color: '#f59e0b',
  },
  {
    template_id: 'maintenance-forecast-review',
    name: 'Monthly Maintenance Forecast Review',
    description: 'Review and update predicted maintenance needs monthly',
    zone: 'operations',
    category: 'reporting',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'monthly', day: '1', time: '09:00' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'predictMaintenanceNeeds' } },
      { action_type: 'send_email', config: { template: 'maintenance_forecast_report' } },
    ],
    difficulty: 'medium',
    estimated_setup_time_minutes: 15,
    use_cases: ['Budget forecasting', 'Plan vendor schedules', 'Reduce emergency callouts'],
    related_entities: ['MaintenanceForecast', 'Property'],
    related_functions: ['predictMaintenanceNeeds'],
    is_popular: true,
    icon: '🔮',
    color: '#f59e0b',
  },
  {
    template_id: 'contractor-assignment-rule',
    name: 'Smart Contractor Assignment',
    description: 'Auto-assign maintenance requests to contractors based on skill/location',
    zone: 'operations',
    category: 'automation',
    trigger_type: 'entity_create',
    trigger_config: { entity: 'MaintenanceRequest', event: 'create' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'assignContractorToTask' } },
      { action_type: 'send_notification', config: { recipient: 'contractor' } },
    ],
    difficulty: 'advanced',
    estimated_setup_time_minutes: 30,
    use_cases: ['Reduce manual assignment', 'Faster response times', 'Improve SLA compliance'],
    related_entities: ['MaintenanceRequest', 'Vendor'],
    related_functions: ['assignContractorToTask'],
    is_popular: false,
    icon: '🤖',
    color: '#f59e0b',
  },

  // BLOCK MANAGEMENT ZONE
  {
    template_id: 'service-charge-calc-quarterly',
    name: 'Quarterly Service Charge Calculation',
    description: 'Auto-calculate and bill service charges every quarter',
    zone: 'block-management',
    category: 'reporting',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'quarterly', month: 'Jan' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'calculateServiceCharges' } },
      { action_type: 'send_email', config: { template: 'service_charge_bill', recipient: 'leaseholders' } },
    ],
    difficulty: 'advanced',
    estimated_setup_time_minutes: 45,
    use_cases: ['Streamline billing', 'Improve tenant satisfaction', 'Regulatory compliance'],
    related_entities: ['ServiceCharge', 'Unit'],
    related_functions: [],
    is_popular: true,
    icon: '💰',
    color: '#3b82f6',
  },
  {
    template_id: 'rtm-renewal-alert',
    name: 'RTM Renewal Alert (2 years)',
    description: 'Alert 2 years before RTM company dissolution',
    zone: 'block-management',
    category: 'alerts',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'daily' },
    actions: [
      { action_type: 'send_email', config: { template: 'rtm_renewal_2year' } },
      { action_type: 'create_task', config: { title: 'RTM Renewal Planning', priority: 'medium' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 5,
    use_cases: ['Plan renewals early', 'Avoid service disruption'],
    related_entities: ['RTMManagement', 'Property'],
    related_functions: [],
    is_popular: false,
    icon: '🏢',
    color: '#3b82f6',
  },

  // TENANT ZONE
  {
    template_id: 'tenant-onboarding-workflow',
    name: 'Tenant Onboarding Workflow',
    description: 'Auto-send welcome docs, portal access, key dates to new tenants',
    zone: 'tenants',
    category: 'notifications',
    trigger_type: 'entity_create',
    trigger_config: { entity: 'Tenant', event: 'create' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'generateTenantPortalToken' } },
      { action_type: 'send_email', config: { template: 'tenant_welcome_pack' } },
      { action_type: 'create_event', config: { title: 'Send Portal Access' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 10,
    use_cases: ['Improve tenant experience', 'Reduce support queries', 'Faster occupancy'],
    related_entities: ['Tenant', 'Property'],
    related_functions: ['generateTenantPortalToken'],
    is_popular: true,
    icon: '🎉',
    color: '#8b5cf6',
  },
  {
    template_id: 'deposit-protection-reminder',
    name: 'Deposit Protection Compliance Check',
    description: 'Annual check that deposits are protected within 30 days',
    zone: 'tenants',
    category: 'verification',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'quarterly', month: 'Jan' },
    actions: [
      { action_type: 'send_email', config: { template: 'deposit_compliance_check' } },
      { action_type: 'create_task', config: { title: 'Verify Deposit Protection Status' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 5,
    use_cases: ['Avoid 3x compensation claims', 'Demonstrate compliance', 'Protect against disputes'],
    related_entities: ['DepositProtection', 'Tenant'],
    related_functions: [],
    is_popular: true,
    icon: '🛡️',
    color: '#8b5cf6',
  },

  // OUT-OF-HOURS ZONE
  {
    template_id: 'emergency-callout-escalation',
    name: 'Emergency Callout Escalation',
    description: 'Auto-escalate emergency callouts if not handled within 2 hours',
    zone: 'outofhours',
    category: 'alerts',
    trigger_type: 'entity_create',
    trigger_config: { entity: 'EmergencyCallout', event: 'create' },
    actions: [
      { action_type: 'create_task', config: { priority: 'urgent', title: 'Escalate {{callout_type}}' } },
      { action_type: 'send_notification', config: { recipient: 'manager' } },
    ],
    difficulty: 'medium',
    estimated_setup_time_minutes: 15,
    use_cases: ['Faster emergency response', 'SLA compliance', 'Reduce property damage'],
    related_entities: ['EmergencyCallout'],
    related_functions: ['escalateEmergencyCallout'],
    is_popular: false,
    icon: '🚨',
    color: '#06b6d4',
  },

  // ADMIN ZONE
  {
    template_id: 'daily-backup-automation',
    name: 'Daily Automated Backup',
    description: 'Create daily backup snapshots of critical entities',
    zone: 'admin',
    category: 'cleanup',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'daily', time: '02:00' },
    actions: [
      { action_type: 'invoke_function', config: { function: 'createBackup' } },
      { action_type: 'send_email', config: { template: 'backup_completed', recipient: 'admin' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 10,
    use_cases: ['Data safety', 'Disaster recovery', 'Compliance audit trail'],
    related_entities: ['Backup'],
    related_functions: ['createBackup'],
    is_popular: true,
    icon: '💾',
    color: '#64748b',
  },
  {
    template_id: 'error-monitoring-daily',
    name: 'Daily Error Log Review',
    description: 'Email error summary to admin every morning',
    zone: 'admin',
    category: 'reporting',
    trigger_type: 'scheduled',
    trigger_config: { frequency: 'daily', time: '07:00' },
    actions: [
      { action_type: 'send_email', config: { template: 'error_log_summary', recipient: 'admin' } },
    ],
    difficulty: 'easy',
    estimated_setup_time_minutes: 5,
    use_cases: ['System health monitoring', 'Proactive bug detection', 'User support'],
    related_entities: ['ErrorLog'],
    related_functions: [],
    is_popular: false,
    icon: '⚠️',
    color: '#64748b',
  },
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Create templates
    const created = await base44.entities.AutomationTemplate.bulkCreate(TEMPLATES);

    return Response.json({
      success: true,
      message: `Created ${created.length} automation templates`,
      count: created.length,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});