import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Only admins can generate tokens
    if (user.role !== 'admin') {
      return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
    }

    const { tenant_id } = await req.json();

    if (!tenant_id) {
      return Response.json({ error: 'Tenant ID required' }, { status: 400 });
    }

    // Get tenant details
    const tenant = await base44.entities.Tenant.get(tenant_id);
    
    if (!tenant) {
      return Response.json({ error: 'Tenant not found' }, { status: 404 });
    }

    // Create or get access token
    const token = btoa(`${tenant_id}:${Date.now()}:${Math.random().toString(36).substr(2, 9)}`);
    
    // Get property and unit info
    const property = tenant.property_id ? await base44.entities.Property.get(tenant.property_id) : null;
    const unit = tenant.unit_id ? await base44.entities.Unit.get(tenant.unit_id) : null;

    // Store token in TenantAccessToken entity
    const tokenRecord = await base44.entities.TenantAccessToken.create({
      tenant_id: tenant_id,
      token: token,
      property_id: tenant.property_id || null,
      unit_id: tenant.unit_id || null,
      expires_at: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 90 days
      is_active: true,
      notes: `Generated by ${user.email} on ${new Date().toLocaleDateString()}`,
    });

    // Generate portal URL
    const portalUrl = `${globalThis.location?.origin || 'https://your-app.base44.app'}/tenant-portal?token=${token}`;

    return Response.json({
      success: true,
      token: token,
      portal_url: portalUrl,
      tenant_name: tenant.full_name,
      tenant_email: tenant.email,
      property_name: property?.name || null,
      unit_reference: unit?.unit_reference || null,
      expires_at: tokenRecord.expires_at,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});