import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const {
      recipientEmail,
      property_id,
      alert_type = 'certificate_expiry',
      days_until,
      ruleName = 'Certificate Expiry Alert',
      ruleCode = 'CERT_EXPIRY',
      description,
      penalties = 'Inability to let property, legal penalties under Housing Act 2004',
      enforcementBody = 'Local Authority / Health & Safety Executive',
    } = await req.json();

    // Determine recipient
    let recipient = recipientEmail;
    if (!recipient && property_id) {
      const prop = await base44.entities.Property.get(property_id);
      recipient = prop?.created_by || Deno.env.get('SALES_LEAD_EMAIL');
    }
    if (!recipient) {
      return Response.json({ error: 'No recipient email provided' }, { status: 400 });
    }

    // Build subject and body based on alert type
    let subject = '';
    let body = '';

    if (alert_type === 'certificate_expiry' || alert_type === 'overdue') {
      subject = `URGENT: ${ruleName} - ${days_until ? days_until + ' days remaining' : 'Action Required'}`;
      body = `
COMPLIANCE ALERT - IMMEDIATE ACTION REQUIRED

This compliance obligation requires immediate attention.

Rule: ${ruleName}
Code: ${ruleCode}
${days_until ? `Days Remaining: ${days_until}` : ''}

${description || 'See system for full details'}

═══════════════════════════════════════════════════════════════════

REQUIRED ACTIONS:
1. Review this compliance requirement immediately
2. Determine what action(s) are needed
3. Document evidence of compliance
4. Update the status in the compliance system
5. Report to management if legal action is at risk

═══════════════════════════════════════════════════════════════════

POTENTIAL CONSEQUENCES OF NON-COMPLIANCE:
${penalties}

Enforcement Body: ${enforcementBody}

═══════════════════════════════════════════════════════════════════

Log in to your compliance system immediately to view full details.
This is an automated alert generated by your compliance management system.
`;
    } else if (alert_type === 'upcoming') {
      subject = `Compliance Reminder - ${ruleName}`;
      body = `
COMPLIANCE REMINDER

The following compliance rule is due for action within the next ${days_until || 30} days:

Rule: ${ruleName}
Code: ${ruleCode}

${description || 'See system for full details'}

Please log in to your compliance system to view deadline details and plan compliance activities.
`;
    } else if (alert_type === 'urgent') {
      subject = `⚠️ CRITICAL: ${ruleName} - Urgent Action Required`;
      body = `
CRITICAL COMPLIANCE ALERT

This compliance issue requires URGENT attention within 48 hours.

Rule: ${ruleName}
${description || 'See system for details'}

Take action immediately or contact your compliance officer.
`;
    }

    await base44.integrations.Core.SendEmail({
      to: recipient,
      subject: subject,
      body: body,
      from_name: 'Compliance Management System',
    });

    // Log the alert sent
    await base44.asServiceRole.entities.AuditLog.create({
      action: 'compliance.alert_sent',
      entity_type: 'ComplianceRule',
      user_email: user.email,
      changes: {
        recipient: recipient,
        alert_type: alert_type,
        rule_name: ruleName,
        days_until: days_until,
      },
      status: 'success',
      timestamp: new Date().toISOString(),
    });

    return Response.json({
      success: true,
      message: `Alert sent to ${recipient}`,
    });
  } catch (error) {
    console.error('Error sending compliance alert:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});