import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user?.role === 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const {
      recipientEmail,
      ruleName,
      ruleCode,
      description,
      penalties,
      enforcementBody,
      alertType = 'overdue', // overdue, upcoming, urgent
    } = await req.json();

    let subject = '';
    let body = '';

    if (alertType === 'overdue') {
      subject = `URGENT: Compliance Rule Overdue - ${ruleName}`;
      body = `
        COMPLIANCE ALERT - IMMEDIATE ACTION REQUIRED
        
        This compliance obligation is now OVERDUE and requires immediate attention.
        
        Compliance Rule: ${ruleName}
        Rule Code: ${ruleCode}
        
        Description:
        ${description || 'See system for full details'}
        
        ═══════════════════════════════════════════════════════════════════
        
        REQUIRED ACTIONS:
        1. Review this compliance requirement immediately
        2. Determine what action(s) are needed
        3. Document evidence of compliance
        4. Update the status in the compliance system
        5. Report to management if legal action is at risk
        
        ═══════════════════════════════════════════════════════════════════
        
        POTENTIAL CONSEQUENCES OF NON-COMPLIANCE:
        ${penalties || 'Contact your legal advisor for specific penalty information'}
        
        Enforcement Body: ${enforcementBody || 'Contact your legal advisor'}
        
        ═══════════════════════════════════════════════════════════════════
        
        Log in to your compliance system immediately to:
        - View full compliance rule details
        - Create an action plan
        - Assign tasks to team members
        - Upload evidence documents
        - Track progress toward compliance
        
        This is an automated alert generated by your compliance management system.
        Time-sensitive — do not ignore.
      `;
    } else if (alertType === 'upcoming') {
      subject = `Compliance Reminder - ${ruleName} Due Soon`;
      body = `
        COMPLIANCE REMINDER
        
        The following compliance rule is due for action within the next 30 days:
        
        Compliance Rule: ${ruleName}
        Rule Code: ${ruleCode}
        
        ${description || 'See system for full details'}
        
        Please log in to your compliance system to:
        - View deadline details
        - Plan compliance activities
        - Assign responsibilities
        - Schedule any required assessments
        
        Log in now: [Link to compliance dashboard]
      `;
    } else if (alertType === 'urgent') {
      subject = `⚠️ CRITICAL: Compliance Rule Requires Urgent Action - ${ruleName}`;
      body = `
        CRITICAL COMPLIANCE ALERT
        
        This compliance issue requires URGENT attention within 48 hours.
        
        Compliance Rule: ${ruleName}
        
        ${description || 'See system for details'}
        
        Escalation in effect. Management notification sent.
        
        Take action immediately or contact your compliance officer.
      `;
    }

    await base44.integrations.Core.SendEmail({
      to: recipientEmail,
      subject: subject,
      body: body,
      from_name: 'Compliance Management System',
    });

    // Log the alert sent
    await base44.asServiceRole.entities.AuditLog.create({
      action: 'compliance.alert_sent',
      entity_type: 'ComplianceRule',
      user_email: user.email,
      changes: {
        recipient: recipientEmail,
        alert_type: alertType,
        rule_name: ruleName,
      },
      status: 'success',
      timestamp: new Date().toISOString(),
    });

    return Response.json({
      success: true,
      message: `Alert sent to ${recipientEmail}`,
    });
  } catch (error) {
    console.error('Error sending compliance alert:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});